name: Combile Rust to WebAssembly

on: push

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
    - uses: mymindstorm/setup-emsdk@v13
    - name: Verify
      run: emcc -v

    - name: Update Rust
      run: rustup update beta && rustup default beta
    - name: Verify Rust
      run: rustc --version

    - name: Add emscripten to rustc
      run: rustup target add  wasm32-unknown-emscripten
      
    - uses: actions/checkout@v3
    - name: Verify ls 
      run: ls -R 
    - name: Build
      run: cargo build --verbose --target wasm32-unknown-emscripten --release
    - name: Verify ls build 
      run: ls -R ./target/wasm32-unknown-emscripten/release/
      
    - name: Gather target outputs 
      run: mkdir biowasm && cp ./target/wasm32-unknown-emscripten/release/biowasmrust.js biowasm && cp ./target/wasm32-unknown-emscripten/release/biowasmrust.wasm biowasm && cp ./target/wasm32-unknown-emscripten/release/deps/biowasmrust.data biowasm
    - name: Verify  biowasm
      run: ls -Rl biowasm
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
          # Upload entire repository
          path: 'biowasm/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4


